CREATE TYPE ingredient_category AS ENUM ('cannabinoid', 'carrier', 'flavor');
CREATE TYPE packaging_category AS ENUM ('bottles', 'droppers');

CREATE TABLE IF NOT EXISTS ingredients (
    id VARCHAR(4) PRIMARY KEY,
    name Text NOT NULL,
    ppg DECIMAL NOT NULL,
    category ingredient_category
);

CREATE TABLE IF NOT EXISTS packaging (
    id VARCHAR(4) PRIMARY KEY,
    name VARCHAR NOT NULL,
    cpu DECIMAL NOT NULL,
    category packaging_category
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    t_volume INTEGER NOT NULL,
    canna_id VARCHAR(4) REFERENCES cannabinoids(id),
    canna_concentration INTEGER NOT NULL,
    carrier_id VARCHAR(4) REFERENCES carriers(id),
    carrier_percentage DECIMAL NOT NULL, 
    flavor_id VARCHAR(4) REFERENCES flavors(id),
    bottle_id VARCHAR(4) REFERENCES bottles(id),
    dropper_id VARCHAR(4) REFERENCES droppers(id),
    total_cpu INTEGER NOT NULL
);

-- CREATE TABLE IF NOT EXISTS cannabinoids (
--     id VARCHAR(4) PRIMARY KEY,
--     name Text NOT NULL,
--     ppg DECIMAL NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS carriers (
--     id VARCHAR(4) PRIMARY KEY,
--     name TEXT NOT NULL,
--     ppg DECIMAL NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS flavors (
--     id VARCHAR(4) PRIMARY KEY,
--     name TEXT NOT NULL,
--     ppg DECIMAL NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS bottles (
--     id VARCHAR(4) PRIMARY KEY,
--     name VARCHAR NOT NULL,
--     cpu DECIMAL NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS droppers (
--     id VARCHAR(4) PRIMARY KEY,
--     name VARCHAR NOT NULL,
--     cpu DECIMAL NOT NULL 
-- );